### ISSUE TITLE
Non-mongoose.Schema.ObjectId keys

### ISSUE THREAD

**Issue by konsumer** [jcspencer/mongo-relation#16]
With [`populate()`](http://mongoosejs.com/docs/populate.html), I can use whatever I want as keys, and it will grab the children or understand when I use Numbers to map the relations:

``` javascript
// UserSchema stores an Array of ObjectIds for posts
var UserSchema = new mongoose.Schema({
    _id: Number,
    posts: [Number]
});
// PostSchema stores an ObjectId for the author
var PostSchema = new mongoose.Schema({
    _id: Number,
    title  : String,
    author : Number
});
```

If I run this:

``` javascript
// Attach the plugin
UserSchema.hasMany('Post');
PostSchema.belongsTo('User', {through: 'author'});

var User = mongoose.model('User', UserSchema),
    Post = mongoose.model('Post', PostSchema);

var user = new User();
var post = new Post();

user.posts.append(post, function(err, post){
  // post.author === user._id
  // user.posts.id(post._id) === post._id
});

user.save();
```

I get this:

```
node_modules/mongoose/lib/schema/number.js:201
  throw new CastError('number', value, this.path);
        ^
CastError: Cast to number failed for value "undefined" at path "posts"
    at SchemaNumber.cast (node_modules/mongoose/lib/schema/number.js:201:9)
    at Array.MongooseArray._cast (node_modules/mongoose/lib/types/array.js:114:30)
    at Object.map (native)
    at Array.MongooseArray.push (node_modules/mongoose/lib/types/array.js:268:23)
    at Array.MongooseArray.append (node_modules/mongo-relation/lib/relationships.js:368:28)
    at Object.<anonymous> (doc/fromdocs.js:30:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by konsumer** [comment]
Oops, dumb error. Needed to set `_id`. Sorry for the noise.

``` javascript
var user = new User({_id:6});
var post = new Post({_id:10});
```
